apiVersion: v1
kind: Service
metadata:
  name: ml-platform-admin
  namespace: ml-platform-admin
  labels:
    app.kubernetes.io/name: ml-platform-admin
    app.kubernetes.io/part-of: ml-platform
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP
  selector:
    app.kubernetes.io/name: ml-platform-admin







