apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: enterprise-gateway

resources:
  - namespace.yaml
  - configmap/tf-gpu-sharing.yaml
  - deployment/enterprise-gateway.yaml
  - kyverno/inject-jeg-env.yaml

labels:
  - pairs:
      app.kubernetes.io/part-of: kubeflow
      app.kubernetes.io/component: enterprise-gateway
    includeSelectors: false

