apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kubeflow

resources:
  - authorization-policy.yaml
  - virtual-service-training-job.yaml

labels:
  - pairs:
      app.kubernetes.io/part-of: kubeflow
      app.kubernetes.io/component: istio
    includeSelectors: false

