apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - enterprise-gateway

labels:
  - pairs:
      app.kubernetes.io/part-of: kubeflow
      app.kubernetes.io/component: jupyter-notebook
    includeSelectors: false

