apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

resources:
  - dcgm-exporter-servicemonitor.yaml

labels:
  - pairs:
      app.kubernetes.io/part-of: prometheus-stack
      app.kubernetes.io/component: servicemonitors
    includeSelectors: false

