apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: auth

resources:
  - namespace.yaml
  - configmap.yaml

labels:
  - pairs:
      app.kubernetes.io/part-of: kubeflow
      app.kubernetes.io/component: dex
    includeSelectors: false

